language: rust
rust: stable
cache: cargo
os: linux
dist: bionic
arch: arm64
env:
  DENO_CANARY: true

before_script: git clone --recurse-submodules --depth=50 https://github.com/denoland/deno.git && cd deno

script: cargo build --release --locked
