language: rust
rust: stable
cache: cargo
os: linux
dist: bionic
arch: arm64
env:
  DENO_CANARY: true

install:
  - git clone https://github.com/denoland/deno.git
  - cd deno

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - ls -ah
  - cargo build --release --locked --all-targets -vv
