name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: arm64v8/ubuntu:latest
    timeout-minutes: 60

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: "denoland/deno"
          fetch-depth: 2
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --locked --release --color always

      - name: Zip
        working-directory: target/release
        run: zip -r deno-aarch64-unknown-linux-gnu.zip deno

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/deno-aarch64-unknown-linux-gnu.zip

  release:
    needs: build
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Download Builds
        uses: actions/download-artifact@v2

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "test"
          name: "Test Release"
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          body: "Test Release"
          token: ${{ secrets.GITHUB_TOKEN }}
